"""add comment_id to request_documents

Revision ID: 6aaeeb74725b
Revises: 8c0f0fe18fb3
Create Date: 2026-07-19 10:14:08.786301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaeeb74725b'
down_revision: Union[str, Sequence[str], None] = '8c0f0fe18fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_documents', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_request_documents_comment_id_request_comments'), 'request_documents', 'request_comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_request_documents_comment_id_request_comments'), 'request_documents', type_='foreignkey')
    op.drop_column('request_documents', 'comment_id')
    # ### end Alembic commands ###
