"""initial schema

Revision ID: 7fe16b3def34
Revises: 
Create Date: 2026-07-12 10:15:27.460027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe16b3def34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_resident', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('code', name=op.f('uq_agents_code'))
    )
    op.create_table('buyer_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyer_companies')),
    sa.UniqueConstraint('name', name=op.f('uq_buyer_companies_name'))
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currencies')),
    sa.UniqueConstraint('code', name=op.f('uq_currencies_code'))
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisions')),
    sa.UniqueConstraint('name', name=op.f('uq_divisions_name'))
    )
    op.create_table('document_types',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('PURCHASE', 'PAYMENT_AGENT', 'PAYMENT_BANK', name='document_category'), nullable=False),
    sa.Column('is_required_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_document_types'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('RUKOVODITEL', 'ISPOLNITEL', 'ZAKAZCHIK', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('STATUS_CHANGE', 'FIELD_CHANGE', 'FILE_UPLOAD', 'FILE_DELETE', 'EXECUTOR_ASSIGNED', 'REJECTED', 'ACKNOWLEDGED_REJECTION', 'CONFIRMED_EXECUTION', 'DOCUMENTS_CONFIRMED', 'DELEGATION_STARTED', 'DELEGATION_ENDED', 'DELEGATION_REVOKED', 'LOGIN', 'LOGOUT', name='audit_action_type'), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegate_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('start_date <= end_date', name=op.f('ck_delegations_ck_delegation_start_before_end')),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], name=op.f('fk_delegations_delegate_id_users')),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], name=op.f('fk_delegations_delegator_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delegations'))
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_exchange_rates_currency_id_currencies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rates')),
    sa.UniqueConstraint('currency_id', 'rate_date', name='uq_exchange_rate_currency_date')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('PAYMENT', 'PURCHASE', 'CONSULTATION', name='request_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'NEW', 'IN_PROGRESS', 'CLARIFICATION', 'REJECTED', 'ARCHIVED', 'AWAITING_CUSTOMER_CONFIRMATION', 'DOCUMENT_CHECK', 'CLOSED', name='request_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_requests_created_by_id_users')),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name=op.f('fk_requests_division_id_divisions')),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], name=op.f('fk_requests_executor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('number', name=op.f('uq_requests_number'))
    )
    op.create_table('consultation_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('question_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_consultation_requests_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_consultation_requests'))
    )
    op.create_table('payment_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('payment_purpose', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_country', sa.String(length=128), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('recipient_bank', sa.String(length=255), nullable=False),
    sa.Column('account_number_iban', sa.String(length=64), nullable=False),
    sa.Column('swift_bic', sa.String(length=16), nullable=False),
    sa.Column('additional_payment_info', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Enum('BANK', 'AGENT', name='payment_method'), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('rate_at_request', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount_rub_at_request', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('rate_at_execution', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount_rub_at_execution', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_payment_requests_agent_id_agents')),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], name=op.f('fk_payment_requests_currency_id_currencies')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_payment_requests_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_payment_requests'))
    )
    op.create_table('purchase_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('buyer_company_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('BANK', 'AGENT', name='payment_method'), nullable=False),
    sa.Column('markup_notes', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['buyer_companies.id'], name=op.f('fk_purchase_requests_buyer_company_id_buyer_companies')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_purchase_requests_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_purchase_requests'))
    )
    op.create_table('request_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_request_comments_author_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_comments_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_comments'))
    )
    op.create_table('request_document_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=16), nullable=False),
    sa.Column('is_required_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_types.code'], name=op.f('fk_request_document_requirements_document_type_code_document_types')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_document_requirements_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_document_requirements'))
    )
    op.create_table('request_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_types.code'], name=op.f('fk_request_documents_document_type_code_document_types')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_documents_request_id_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_request_documents_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_documents'))
    )
    op.create_table('request_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'NEW', 'IN_PROGRESS', 'CLARIFICATION', 'REJECTED', 'ARCHIVED', 'AWAITING_CUSTOMER_CONFIRMATION', 'DOCUMENT_CHECK', 'CLOSED', name='request_status'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'NEW', 'IN_PROGRESS', 'CLARIFICATION', 'REJECTED', 'ARCHIVED', 'AWAITING_CUSTOMER_CONFIRMATION', 'DOCUMENT_CHECK', 'CLOSED', name='request_status'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_request_status_history_changed_by_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_status_history_request_id_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_status_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_status_history')
    op.drop_table('request_documents')
    op.drop_table('request_document_requirements')
    op.drop_table('request_comments')
    op.drop_table('purchase_requests')
    op.drop_table('payment_requests')
    op.drop_table('consultation_requests')
    op.drop_table('requests')
    op.drop_table('exchange_rates')
    op.drop_table('delegations')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('document_types')
    op.drop_table('divisions')
    op.drop_table('currencies')
    op.drop_table('buyer_companies')
    op.drop_table('agents')
    # ### end Alembic commands ###
    # PostgreSQL не удаляет ENUM-типы автоматически при drop_table —
    # без этого повторный upgrade после downgrade упадёт на "type already exists".
    op.execute("DROP TYPE IF EXISTS request_status")
    op.execute("DROP TYPE IF EXISTS request_type")
    op.execute("DROP TYPE IF EXISTS payment_method")
    op.execute("DROP TYPE IF EXISTS document_category")
    op.execute("DROP TYPE IF EXISTS audit_action_type")
    op.execute("DROP TYPE IF EXISTS user_role")
