"""document_type_code nullable для вспомогательных файлов

Revision ID: 8c0f0fe18fb3
Revises: 7fe16b3def34
Create Date: 2026-07-13 19:46:40.473215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0f0fe18fb3'
down_revision: Union[str, Sequence[str], None] = '7fe16b3def34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_documents', 'document_type_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_documents', 'document_type_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
